model_name: "monai"        # or "pytorch"
in_channels: 4
out_channels: 5
image_size: [128, 128]
batch_size: 8
learning_rate: 0.0001
num_epochs: 50
patience: 5
data_csv: "data/meta_data.csv"
h5_dir: "path/to/h5/files"
